# Site
name: "Muhamad Apriyatna"
title: "Blog Article"
description: "Selamat datang di blog Muhamad Apriyatna 181011401125"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: /mapriyatna.github.io
google_analytics: "UA-xxxxxxxx-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com

# Authors
authors:
  Mapriyatna:
    name: Mapriyatna
    display_name: Mapriyatna
    gravatar: 93273abec768a40ca4a15d187dbf647f
    email: mapriyatna.ay@gmail.com
    web: https:/www.lebakcyber.net
    twitter: https://twitter.com/MApriyatna
    description: "Belajarlah Sebelum Malas"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: false

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
